name: OfficeRenew

on: [ create ]
# on:
#   push:
#     branches: [ master ]
#   schedule:
#     - cron: '*/20 * * * *'

jobs:
  renew:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute script
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: |
          python main.py

      - name: Update refresh_token.txt
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add refresh_token.txt
          git commit -m "Update refresh_token.txt"
          git push
