name: OfficeRenew

on:
  workflow_dispatch:
    inputs:
      times:
        description: 'Script run times'
        required: false
        default: 5
  push:
    branches: [ master ]
  schedule:
    - cron: '0 */2 * * *'

jobs:
  renew:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute script
        env:
          RUN_TIMES: ${{ github.event.inputs.times }}
          GITHUB_REPO: ${{ github.repository }}
          ACTION_TOKEN: ${{ secrets.ACTION_TOKEN }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_URI: ${{ secrets.CLIENT_URI }}
          CLIENT_TOKEN: ${{ secrets.CLIENT_TOKEN }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: |
          python main.py

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 1
          keep_minimum_runs: 0
